
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]
    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017
        env:
          MONGO_HOST: "0.0.0.0"
          MONGO_USER: mongo
          MONGO_PASSWORD: mongo
          MONGO_DATABASE_NAME: mongo
          MONGO_PORT: ${{ job.services.mongodb.ports[27017] }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Create env file
      run: |
        touch .env
        echo SBF_CHALLENGE_HOST="0.0.0.0" >> .env
        echo SBF_CHALLENGE_PORT=8000 >> .env
        echo SBF_CHALLENGE_WORKERS_COUNT=1 >> .env
        echo SBF_CHALLENGE_RELOAD=True >> .env
        echo SBF_CHALLENGE_CURRENCY_API_URL="https://api.exchangerate.host" >> .env
        echo SBF_CHALLENGE_MONGO_HOST='0.0.0.0' >> .env
        echo SBF_CHALLENGE_MONGO_PORT=27017 >> .env
        echo SBF_CHALLENGE_MONGO_USER=mongo >> .env
        echo SBF_CHALLENGE_MONGO_PASSWORD=mongo >> .env
        echo SBF_CHALLENGE_MONGO_DATABASE_NAME=mongo >> .env
        echo SBF_CHALLENGE_MONGO_MAX_CONNECTIONS_COUNT=10 >> .env
        echo SBF_CHALLENGE_MONGO_MIN_CONNECTIONS_COUNT=10 >> .env
        cat .env
    - name: Install Dependencies
      run: |
        make dependencies
    - name: Run Lint
      run: |
        make lint
    - name: Run Tests
      run: |
        make test-coverage


