
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]
    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017
        env:
          MONGO_HOST: 0.0.0.0
          MONGO_PORT: 27017
          MONGO_USER: root
          MONGO_PASSWORD: root
          MONGO_DATABASE_NAME: sbf_challenge
          MONGO_MAX_CONNECTIONS_COUNT: 10
          MONGO_MIN_CONNECTIONS_COUNT: 10


    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Create env file
      run: make copy-envs
    - name: Install Dependencies
      run: |
        make dependencies
    - name: Run Lint
      run: |
        make lint
    - name: Run Tests
      env:
          MONGO_HOST: 0.0.0.0
          MONGO_PORT: 27017
          MONGO_USER: root
          MONGO_PASSWORD: root
          MONGO_DATABASE_NAME: sbf_challenge
      run: |
        make test-coverage


